export type Source = 'google' | 'treatwell'

export interface Review {
  name: string
  initials: string
  color: string
  source: Source
  date: string
  stars: number
  verified?: boolean
  text: string
  photoFilename?: string
}

export const REVIEWS: Review[] = [
  { name: 'Sepideh', initials: 'S', color: '#B06A8A', source: 'treatwell', date: '2 maanden geleden', stars: 5, verified: true, text: 'en ik ben nog steeds zo blij met het resultaat! Chiva dacht heel goed met me mee en luisterde naar mijn wensen en gaf eerlijk advies. Ze nam echt de tijd! Omdat mijn ogen wat meer uitdaging geven vond ik het best spannend, maar het is haar prachtig gelukt. Je merkt echt dat ze zich onderscheidt van anderen door haar persoonlijke aandacht en passie voor haar werk. Het resultaat is precies wat ik hoopte ✨' },
  { name: 'Cansu', initials: 'C', color: '#2AA8A0', source: 'treatwell', date: '4 maanden geleden', stars: 5, verified: true, text: 'Super tevreden met mijn nieuwe wimpers! Bedankt dat je uitgebreid de tijd hebt genomen een ook nog eens een mini cursus gekregen. Tot snel!' },
  { name: 'Milva', initials: 'M', color: '#D4782A', source: 'treatwell', date: '5 maanden geleden', stars: 5, verified: true, text: 'I had a great time with chiva. Thank you sooo much and also very gratefull for the listen ear 😊😊' },
  { name: 'Valentina', initials: 'V', color: '#7B6EA8', source: 'treatwell', date: '6 maanden geleden', stars: 5, verified: true, text: 'Loved every bit of it' },
  { name: 'Carii', initials: 'C', color: '#4A9E6E', source: 'treatwell', date: '6 maanden geleden', stars: 5, verified: true, text: 'Chiva is een fijn persoon die haar vak kent en goed uitvoert' },
  { name: 'Petja', initials: 'P', color: '#8B4DB8', source: 'treatwell', date: '8 maanden geleden', stars: 5, verified: true, text: "I'm still new to lashes but I already know I never wanna go to another lash tech!! She is always chill and cheerful and really adapts to your vibe! Wanna talk? Then you'll have some nice conversations and the time flies! Or if you wanna have a little nap and wake up beautiful and STUNNNINGGG! In all my appointments I have not been disappointed! I love trying new things and she has so many options!" },
  { name: 'Linda', initials: 'L', color: '#3B82C4', source: 'treatwell', date: '11 maanden geleden', stars: 5, verified: true, text: 'Ze werkt erg nauwkeurig en wimpers zien er erg mooi en natuurlijk uit ❤️' },
  { name: 'Zara', initials: 'Z', color: '#D4782A', source: 'treatwell', date: '11 maanden geleden', stars: 5, verified: true, text: 'Alles was super duidelijk! Heb zooo veel geleerd. Zeker een aanrader' },
  { name: 'Beatrice', initials: 'B', color: '#7B4D9E', source: 'treatwell', date: 'ongeveer 1 jaar geleden', stars: 5, verified: true, text: 'Awesome, chat, awesome clean working, Happy moments, and 100% satisfaction' },
  { name: 'Avin', initials: 'A', color: '#C97B5A', source: 'treatwell', date: 'meer dan 1 jaar geleden', stars: 5, verified: true, text: 'It was very beautiful and I was really happy with the result of my eyelashes' },
  { name: 'Carii', initials: 'C', color: '#4A9E6E', source: 'treatwell', date: 'meer dan 1 jaar geleden', stars: 5, verified: true, text: 'fijne dame, ze verstaat haar vak! wimpers zijn mooi gezet!' },
  { name: 'Cheely', initials: 'C', color: '#B07A5A', source: 'treatwell', date: 'meer dan 1 jaar geleden', stars: 5, verified: true, text: 'Ze is heel vriendelijk en probeerde me erg op me gemak te stellen wat ook is gelukt!! Ik kom zeker nog een keer langs' },
  { name: 'Melina Yoldas', initials: 'M', color: '#7B6EA8', source: 'google', date: '2 maanden geleden', stars: 5, text: "Onlangs heb ik de lash artist cursus van Chiva gevolgd en ik kan oprecht zeggen dat het een enorme verrijking is geweest voor mijn ontwikkeling als wimperstylist. De inhoud van de training is sterk en diepgaand; er wordt niet alleen gewerkt aan techniek, maar ook aan inzicht, precisie en professionele groei.\n\nWat deze cursus echt onderscheidt, is de manier waarop alles wordt uitgelegd. De uitleg is helder, gedetailleerd en onderbouwd, waardoor je niet alleen leert hoe je iets doet, maar vooral ook waarom.\n\nVoor iedere lash artist die een volgende stap wil zetten in haar carrière en zichzelf serieus wil ontwikkelen, is deze cursus absoluut een aanrader." },
  { name: 'Aisha Castro Kaiser', initials: 'A', color: '#E05C7A', source: 'google', date: '2 maanden geleden', stars: 5, text: "Ik heb bij Chiva de wispy lash artist cursus gevolgd en ik ben zó blij dat ik dit heb gedaan! Ze legt alles super duidelijk uit en neemt echt de tijd voor je.\n\nDoor deze cursus voel ik me veel zelfverzekerder in mijn werk en zie ik echt verschil in mijn resultaten. Echt een aanrader voor elke lash tech die wil groeien tot lash artist ✨" },
  { name: 'Chay Saliji', initials: 'C', color: '#2AA8A0', source: 'google', date: 'een maand geleden', stars: 5, text: "Ik wil even mijn ervaring delen over mijn lash training bij Chiva 🤍\n\nVanaf het eerste moment voelde ik me op mijn gemak. Chiva neemt echt de tijd voor je en ondersteunt je bij elke stap.\n\nIk heb eerder een lash cursus gevolgd, maar daarna had ik eerlijk gezegd niet eens het zelfvertrouwen om op echte ogen te oefenen. Na de cursus van Chiva is dat compleet veranderd.\n\nDit is een investering in jezelf die het écht waard is ✨" },
  { name: 'Nina-li', initials: 'N', color: '#E8784A', source: 'google', date: '6 maanden geleden', stars: 5, text: "Eerste keer wimper extensions bij Chiva laten zetten. Echt een aanrader!\n\nZe denkt met je mee, stelt je op je gemak, neemt de tijd voor je en werkt heel nauwkeurig. 10/10 definitely recommend." },
  { name: 'Maud Lommers', initials: 'M', color: '#4A9E6E', source: 'google', date: '6 maanden geleden', stars: 5, text: 'Beste lash artist ever <3 Ze denkt super goed met je mee en er is heel veel mogelijk. Mn wimpers zijn nog nooit zo mooi geweest' },
  { name: 'mara', initials: 'm', color: '#3B82C4', source: 'google', date: '11 maanden geleden', stars: 5, text: "Ik zeg het je, nadat ik hier ben geweest ben ik nooit ergens anders geweest. She never disappoints. Ik was in het begin heel erg onzeker, maar toen ik het bij lashedbychiva liet doen heb ik nooit ergens last van gehad. Ze luistert echt naar wat je wilt en het is altijd gezellig!! Ik zeg doen ladies!! 🙌" },
  { name: 'Julia Bergen', initials: 'J', color: '#8B4DB8', source: 'google', date: '7 maanden geleden', stars: 5, text: "Ik ben super tevreden! Mijn wimpers blijven echt lang mooi zitten en dat scheelt me zoveel tijd 's ochtends. Daarnaast is ze ontzettend lief en maakt ze je helemaal op je gemak. Echt een aanrader!" },
  { name: 'petja kirkels', initials: 'p', color: '#6B4D9E', source: 'google', date: '6 maanden geleden', stars: 5, text: "Ik zeg het nog een keer: mijn wimpers van Chiva hebben me NOOIT teleurgesteld! Ze heeft zoveel verschillende opties, dus als je af en toe van stijl wilt wisselen, is zij de perfecte keuze! Je raakt er waarschijnlijk verslaafd aan na je eerste set 😫" },
  { name: 'S K', initials: 'S', color: '#D4782A', source: 'google', date: 'een jaar geleden', stars: 5, text: 'Nooit bleven mijn wimpers goed zitten bij andere stylistes, de volgende zag lagen ze er vaak weer af. Bij deze topper zitten ze na 3 weken nog fantastisch!! Zo blij ❤️' },
  { name: 'Jara van den Brenk', initials: 'J', color: '#C97B5A', source: 'google', date: 'een jaar geleden', stars: 5, photoFilename: 'jara-van-den-brenk.jpg', text: 'Ik ben al een aantal keer geweest, ontzettend lieve dame. Ze denkt altijd met je mee, ook een aanrader als je graag bruine lashes wil! 🤎🤗' },
  { name: 'M Mirzojan', initials: 'M', color: '#D45A3A', source: 'google', date: 'een jaar geleden', stars: 5, text: 'Deze dame kan echt hele mooie lashes zetten, ze denkt met je mee en werkt met je oogvorm. Blijven superlang zitten en het is altijd gezellig ❤️' },
  { name: 'nar c', initials: 'n', color: '#2E8B7A', source: 'google', date: 'een jaar geleden', stars: 5, text: 'Ze is super gastvrij en zet de lashes echt goed, ik ben heel blij dat dit mijn vaste lashtag is 🥰' },
  { name: 'Che', initials: 'C', color: '#B05070', source: 'google', date: 'een jaar geleden', stars: 5, photoFilename: 'che.jpg', text: 'Hele aardige dame, ik kwam voor de eerste keer voor wimperextentions en werd erg goed gerustgesteld. En het resultaat was prachtig !!' },
  { name: 'Mäbel Seelen', initials: 'M', color: '#7A6E5A', source: 'google', date: 'een jaar geleden', stars: 5, photoFilename: 'mabel-seelen.jpg', text: 'Deze vrouw is kunstenares. Prachtige set wimpers. En ze is ook nog eens lief!' },
  { name: 'avin abdullah', initials: 'a', color: '#4A6EA8', source: 'google', date: 'een jaar geleden', stars: 5, text: 'Ze is erg aardig en haar werk is erg mooi ❤️❤️❤️❤️🙌🙌🙌' },
  { name: 'Fanity Meier', initials: 'F', color: '#D47A2A', source: 'google', date: 'een jaar geleden', stars: 5, text: 'Ben altijd tevreden als ik weg ga' },
  { name: 'Roroo', initials: 'R', color: '#9B4DB8', source: 'google', date: 'een maand geleden', stars: 5, text: 'Ik heb de wispy cursus gevolgd en heb daar zeker geen spijt van! Ik heb zoveel geleerd en merkte echt dat ze dit met passie doet! Tijdens andere cursussen leerde ik alleen de basis, maar bij haar leer je echt ALLES! Zeker aan te raden! ✨😁' },
  { name: 'H K', initials: 'H', color: '#D45A2A', source: 'google', date: 'een maand geleden', stars: 5, text: 'Super tevreden! De beste in medusa lashes en super vriendelijk! En oh ja de lijm die ze gebruikt? Ge-wel-dig: was verbaasd dat na 3 weken ze nog goed zaten <3' },
  { name: 'Michela Eriu', initials: 'M', color: '#C76A8A', source: 'google', date: 'een maand geleden', stars: 5, photoFilename: 'michela-eriu.jpg', text: 'Ik was al super lang op zoek naar iemand die medusa lashes kon doen. Chiva heeft me echt precies gegeven wat ik wilde. Ik ben er enorm blij mee! Verder is ze heel verwelkomend en vloog de tijd voorbij. Ik kom zeker weer 💗' },
  { name: 'Ifeoluwa Oladipo', initials: 'I', color: '#5A5A7A', source: 'google', date: '2 maanden geleden', stars: 5, photoFilename: 'ifeoluwa-oladipo.jpg', text: 'Ik heb enorm veel geluk gehad dat Chiva mij heeft begeleid. Ze maakte van een technische cursus een fluitje in een cent – ondanks dat het online was! Ze was zo vriendelijk en geduldig en corrigeerde me op een liefdevolle manier. Ik voel me veel zelfverzekerder in mijn vaardigheden na de training met haar.' },
]